# The Dependency-Track host (architecture §6): one instance in a private subnet, reachable for people only
# through SSM Session Manager (ADR-004). It holds no essential state of its own (ADR-021): data lives in
# RDS and the encryption key in Secrets Manager, so replacing it loses nothing.

data "aws_region" "current" {}

data "aws_caller_identity" "current" {}

data "aws_partition" "current" {}

data "aws_ssm_parameter" "ami" {
  name = var.ami_ssm_parameter
}

locals {
  parameter_arn_prefix = "arn:${data.aws_partition.current.partition}:ssm:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:parameter"

  # Created by the owner, by hand, outside Terraform (runbook §1); referenced by name only.
  nvd_api_key_arn = "${local.parameter_arn_prefix}${var.dtrack_parameter_path}/nvd-api-key"

  # Written by the instance, not by Terraform. A Terraform-managed SecureString would copy the key into
  # state on every refresh, and state is readable by the plan role (ADR-019, point 4).
  ci_api_key_arn = "${local.parameter_arn_prefix}${var.dtrack_parameter_path}/ci-api-key"

  # Terraform creates the containers; the instance writes the values, so they never enter state.
  dtrack_secrets = {
    admin        = "Dependency-Track admin password, generated by the instance bootstrap"
    "db-app"     = "Password of the dtrack database role, generated by the instance bootstrap (ADR-022)"
    "secret-key" = "Dependency-Track secret key that encrypts confidential settings in the database (ADR-021)"
  }
}

resource "aws_cloudwatch_log_group" "this" {
  name              = var.log_group_name
  retention_in_days = var.log_retention_days
}

resource "aws_secretsmanager_secret" "dtrack" {
  for_each = local.dtrack_secrets

  name        = "${var.dtrack_secret_prefix}/${each.key}"
  description = each.value

  # The secrets live exactly as long as the environment. Without this, a deleted secret would block a new
  # one with the same name for the next session (runbook §6).
  recovery_window_in_days = 0
}

# Opens the startup barrier (ADR-020): the instance sets it to "done" only after verifying that the default
# credentials no longer work. Terraform owns it, so every new environment starts at "pending" and a stale
# "done" from an earlier session can never open the barrier early.
resource "aws_ssm_parameter" "bootstrap_status" {
  name        = "${var.dtrack_parameter_path}/bootstrap-status"
  description = "Instance bootstrap progress: pending until the default Dependency-Track login is verified to fail"
  type        = "String"
  value       = "pending"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_instance" "this" {
  # A newer AMI replaces the instance on the next apply. That is safe by design (ADR-021).
  ami           = data.aws_ssm_parameter.ami.insecure_value
  instance_type = var.instance_type

  subnet_id                   = var.subnet_id
  vpc_security_group_ids      = [var.security_group_id]
  associate_public_ip_address = false
  iam_instance_profile        = aws_iam_instance_profile.this.name
  # No key_name: there is no SSH access at all (ADR-004).

  user_data_base64            = var.user_data_base64
  user_data_replace_on_change = true

  # IMDSv2 only, against SSRF-style credential theft. Hop limit 2 lets containers reach the role.
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
    instance_metadata_tags      = "disabled"
  }

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size
    encrypted             = true
    delete_on_termination = true
  }

  tags = {
    Name = "${var.name_prefix}-dtrack"
  }

  # The bootstrap starts at first boot and needs its permissions, secrets and status parameter right away.
  depends_on = [
    aws_iam_role_policy.instance,
    aws_iam_role_policy_attachment.ssm_core,
    aws_cloudwatch_log_group.this,
    aws_secretsmanager_secret.dtrack,
    aws_ssm_parameter.bootstrap_status,
  ]
}
